### ISSUE TITLE
Making classification of meetups clearer

### ISSUE THREAD

**Issue by alaskaa** [charlottebrf/coder-newbie-advice#25]
I thought I'd drop this in here for some discussion! 

I think it might make sense to clarify in the meetups section that we're actively trying to collate meetups where people can go and learn programming (rather than attending just talks). I had the impression that that is what you were trying to collect (and listing meetups for talks and languages just generally under: search on meetup) but I think it could maybe be clarified somewhere. Do you agree? 

While talks are great, there are hundreds of talk-based meetups but having those that you can actually attend to learn or where you can go and ask for help, might make even more of difference - and these are hard to find. What do you think? Would love to make this the one-stop place for find all this information.

Happy to submit a PR myself to fix it, but thought I'd discuss first.

**Comment by charlottebrf** [comment]
Yes this is a really good point you make. I was a bit overwhelmed by the meetup scene as you say there's so many that are relevant to tech industry & getting a career, but which aren't learning to code meetups. 

Your impression was correct, I thought to limit to be ones where people can learn to program. Great happy for a PR. Thanks for being so active here, really appreciate it. Just blown away by the support :)

**Comment by alaskaa** [comment]
I've made a PR here https://github.com/charlottebrf/coder-newbie-advice/pull/36 that adds a sentence to make this clearer. Let me know if it needs reworked and I am happy to amend. Didn't want to make it too long though :) 

And no problem at all, as I mentioned before, I think it is a great idea to bundle these all together an dI think many people will benefit from it - especially if we start making it into a website!

**Comment by charlottebrf** [comment]
Thanks @alaskaa I'll close this as it's now added in
