### ISSUE TITLE
Arrange resources by set curriculum vs individual exercises

### ISSUE THREAD

**Issue by alaskaa** [charlottebrf/coder-newbie-advice#6]
Some of the free resources listed offer a set curriculum you can work through and gain a certificate at the end, like freeCodeCamp and The Odin Project, whereas others have more individual exercises. I wondered whether it would make sense to cluster the resources in a way like that, or another, before the list gets too long!

What do you think? Happy to discuss!

**Comment by charlottebrf** [comment]
That's a really good point thanks for flagging @alaskaa. I've added in some extra headers now in the online resources to give an indication of if they're for a specific project. Do you think we should add in another subtitle for Certificates & add those in there? I guess people don't have to get a certificate if they don't want to but could be good to flag that they can if they want...

**Comment by alaskaa** [comment]
I think especially for people who maybe do not attend a bootcamp or study the subject at university, certificates can (don't have to) indicate that people have invested a significant amount of time into completing a course and often do free-form projects too! I remember that those were things that I found important when I started working on front-end development and I often see certificates shared around on Twitter because they seem to give people a sense of accomplishment. So yes, I think it would be great to add in. We could add something along the lines of: "has the option of gaining certificates of completion for finishing a learning path" - but that would indicate that there is the option (but it is not mandatory).

**Comment by charlottebrf** [comment]
Cool ok will get tomorrow @alaskaa 👍

**Comment by charlottebrf** [comment]
What do you think about the way I added the certificate possibilities @alaskaa ? Ok to close this issue? Thank you

**Comment by alaskaa** [comment]
I think I only commented on the actual commit this morning! Yes, I think you solved that well now by introducing these headings! So I think this issue can be closed.

**Comment by charlottebrf** [comment]
Thanks 👍
